// <auto-generated />
using System;
using AzerothPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzerothPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AzerothCoreDbContext))]
    partial class AzerothCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AzerothPlatform.Infrastructure.Data.Entities.CatalogModuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CatalogModules", (string)null);
                });

            modelBuilder.Entity("AzerothPlatform.Infrastructure.Data.Entities.CloudProviderConnectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultRegion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedCredentials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CloudProviderConnections", (string)null);
                });

            modelBuilder.Entity("AzerothPlatform.Infrastructure.Data.Entities.CloudSshKeyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSshUser")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CloudSshKeys", (string)null);
                });

            modelBuilder.Entity("AzerothPlatform.Infrastructure.Data.Entities.CloudAuditLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("CloudAuditLogs", (string)null);
                });

            modelBuilder.Entity("AzerothPlatform.Infrastructure.Data.Entities.ManagedStackEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AdminAccountInitializedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AppliedPatchLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppliedPatchesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplyRunId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApplyStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplyingPatchKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmoryEmailConfigJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArmoryEmailConfigured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArmoryEmailSmtpPasswordProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArmoryEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmoryPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArmorySessionSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmoryDatabasePasswordProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArmoryUseEmailConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ClientEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigMigrationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoreBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreCommitSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreRepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomEnvVarsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabasePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseRootPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentTarget")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalSshPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalSshPrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSshUser")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdminAccountInitialized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCoreOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBuiltAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdateCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestAvailableCoreSha")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestCoreBuildChecksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestCoreBuildStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestCoreBuildStatusCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LauncherClientVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LauncherDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LauncherDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LauncherSortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LauncherTemplate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LauncherVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleVersionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedStackName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutdatedModuleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutdatedModulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostBuildAction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishBindAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmlistHostOverride")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuntimeArtifactVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceEnvVarsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoapPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoapPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoapUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorldServerPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedStackName")
                        .IsUnique();

                    b.ToTable("ManagedStacks", (string)null);
                });

            modelBuilder.Entity("AzerothPlatform.Infrastructure.Data.Entities.StackRevisionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AppliedPatchLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppliedPatchesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreCommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleVersionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StackId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StackId");

                    b.ToTable("StackRevisions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
