namespace AzerothPlatform.Infrastructure.Services;

/// <summary>
/// Versioning for the per-stack runtime artifacts the manager generates (the <c>.env</c> and
/// <c>docker-compose.override.yml</c> written by <c>StackService.EnsureRuntimeConfigurationAsync</c>).
///
/// <para>
/// When those artifacts are (re)generated, the manager stamps the stack with
/// <see cref="CurrentVersion"/>. A stack whose stored version is lower was generated by an older
/// manager, so its on-disk artifacts may be missing later security or behaviour fixes — a stack that
/// predates the data-plane host-bind policy keeps publishing MySQL and SOAP on all interfaces until it
/// is re-applied. Such a stack is flagged "re-apply required" so an operator can regenerate them.
/// </para>
///
/// <para>
/// <see cref="CurrentVersion"/> must be bumped whenever the generated <c>.env</c> /
/// <c>docker-compose.override.yml</c> output changes in a way existing stacks should pick up (host-bind
/// policy, new or renamed variables, service topology). Without the bump, drifted stacks are never
/// flagged and keep running the old artifacts indefinitely. Record what changed in <see cref="History"/>.
/// </para>
/// </summary>
public static class RuntimeArtifactTemplate
{
    /// <summary>
    /// Current runtime-artifact template version. Stacks stamped with a lower value are considered drifted
    /// and are surfaced as "re-apply required".
    /// </summary>
    public const int CurrentVersion = 1;

    /// <summary>
    /// Human-readable changelog for the runtime-artifact template, newest first. Keep in sync with
    /// <see cref="CurrentVersion"/>.
    /// </summary>
    public static readonly IReadOnlyList<string> History = new[]
    {
        "v1: Baseline",
    };
}
