namespace AzerothPlatform.Infrastructure.Services;

/// <summary>
/// Versioning for the per-stack runtime artifacts the manager generates (the <c>.env</c> and
/// <c>docker-compose.override.yml</c> written by <c>StackService.EnsureRuntimeConfigurationAsync</c>).
///
/// <para>
/// When those artifacts are (re)generated, the manager stamps the stack with
/// <see cref="CurrentVersion"/>. A stack whose stored version is lower than <see cref="CurrentVersion"/>
/// was generated by an older manager and its on-disk artifacts may be missing later security/behavior
/// fixes (this is the "deployment drift" problem: e.g. a stack generated before the data-plane host-bind
/// fix keeps publishing MySQL/SOAP on all interfaces until it is re-applied). Such a stack is flagged as
/// "re-apply required" so an operator can restart/re-apply it to regenerate the artifacts.
/// </para>
///
/// <para>
/// IMPORTANT: bump <see cref="CurrentVersion"/> whenever the generated <c>.env</c> /
/// <c>docker-compose.override.yml</c> output changes in a way that existing stacks should pick up
/// (host-bind policy, new/renamed variables, service topology, etc.). Add a short note to
/// <see cref="History"/> describing what changed.
/// </para>
/// </summary>
public static class RuntimeArtifactTemplate
{
    /// <summary>
    /// Current runtime-artifact template version. Stacks stamped with a lower value are considered drifted
    /// and are surfaced as "re-apply required".
    /// </summary>
    public const int CurrentVersion = 1;

    /// <summary>
    /// Human-readable changelog for the runtime-artifact template, newest first. Keep in sync with
    /// <see cref="CurrentVersion"/>.
    /// </summary>
    public static readonly IReadOnlyList<string> History = new[]
    {
        "v1: baseline versioning. Host-interface bind policy (loopback-by-default data plane for local " +
        "stacks; optional ExternalDataPlaneBindAddress for external stacks) is the reference template.",
    };
}
