namespace AzerothPlatform.Infrastructure.Services;

/// <summary>
/// Responsive shell rules for the armory page wrapper. Written to <c>css/azp-responsive.css</c> on every
/// image rebuild so older uploaded <c>theme.css</c> bundles cannot keep a fixed-width container.
/// </summary>
internal static class ArmoryResponsiveTheme
{
    public const string StylesheetFileName = "azp-responsive.css";

    public static string BuildCss() =>
        """
        /* Generated by AzerothPlatform — responsive shell rules. Do not edit. */
        @media screen and (max-width: 1200px) {
          .section {
            width: 100% !important;
            max-width: none !important;
            padding-left: 0 !important;
            padding-right: 0 !important;
            margin-left: 0 !important;
            margin-right: 0 !important;
          }

          .armory-container {
            width: 100% !important;
            max-width: none !important;
            margin-left: 0 !important;
            margin-right: 0 !important;
            border-radius: 0 !important;
            border-left: none !important;
            border-right: none !important;
            box-sizing: border-box !important;
          }
        }
        """;
}
