using System.Globalization;
using System.Text;
using AzerothPlatform.Core.Contracts;

namespace AzerothPlatform.Infrastructure.Services;

/// <summary>
/// Generates per-widget layout CSS (<c>css/azp-layout.css</c>) from saved layout settings. Chrome
/// overrides layer on top of the global armory theme without editing bundled templates.
/// </summary>
internal static class ArmoryLayoutTheme
{
    public static string BuildCss(ArmoryLayoutDto layout)
    {
        var normalized = ArmoryLayoutDefaults.Normalize(layout);
        if (normalized.Pages.Count == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        sb.AppendLine("/* Generated by AzerothPlatform — per-page grid config + widget chrome overrides. */");
        sb.AppendLine("/* Base grid, mobile, and widget-type styles live in the bundled theme.css. */");
        sb.AppendLine();

        foreach (var (pageId, page) in normalized.Pages.OrderBy(entry => entry.Key, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine($"[data-armory-page=\"{EscapeCss(pageId)}\"] {{");
            sb.AppendLine($"  grid-template-columns: repeat({page.Grid.Columns}, minmax(0, 1fr));");
            sb.AppendLine($"  gap: {page.Grid.Gap}px;");
            sb.AppendLine($"  grid-auto-rows: minmax({page.Grid.RowHeight}px, auto);");
            sb.AppendLine("}");
            sb.AppendLine();

            foreach (var widget in page.Widgets.Where(w => w.Visible))
            {
                AppendWidgetChrome(sb, pageId, widget);
            }
        }

        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    /// <summary>
    /// Ensures the deployed <c>layout.hbs</c> references generated theme and layout CSS files.
    /// </summary>
    public static void EnsureLayoutStylesheetLinked(string staticPath)
    {
        var layoutPath = Path.Combine(staticPath, "layout.hbs");
        if (!File.Exists(layoutPath))
        {
            return;
        }

        var content = File.ReadAllText(layoutPath);
        var updated = content;

        if (File.Exists(Path.Combine(staticPath, "css", "azp-theme.css"))
            && !content.Contains("azp-theme.css", StringComparison.Ordinal))
        {
            updated = InsertStylesheetLink(updated, "azp-theme.css", "theme.css");
        }

        if (File.Exists(Path.Combine(staticPath, "css", "azp-layout.css"))
            && !updated.Contains("azp-layout.css", StringComparison.Ordinal))
        {
            updated = InsertStylesheetLink(updated, "azp-layout.css", "azp-theme.css", "theme.css");
        }

        if (!string.Equals(content, updated, StringComparison.Ordinal))
        {
            File.WriteAllText(layoutPath, updated);
        }
    }

    private static string InsertStylesheetLink(
        string content,
        string cssFile,
        string primaryAnchor,
        string? fallbackAnchor = null)
    {
        var link =
            $"    <link rel=\"stylesheet\" type=\"text/css\" href=\"{{{{websiteRoot}}}}/css/{cssFile}\">\n";

        foreach (var anchor in new[] { primaryAnchor, fallbackAnchor }.Where(static item => !string.IsNullOrWhiteSpace(item)))
        {
            var typed = $"<link rel=\"stylesheet\" type=\"text/css\" href=\"{{{{websiteRoot}}}}/css/{anchor}\">";
            if (content.Contains(typed, StringComparison.Ordinal))
            {
                return content.Replace(typed, typed + "\n" + link.TrimEnd(), StringComparison.Ordinal);
            }

            var plain = $"<link rel=\"stylesheet\" href=\"{{{{websiteRoot}}}}/css/{anchor}\">";
            if (content.Contains(plain, StringComparison.Ordinal))
            {
                return content.Replace(plain, plain + "\n" + link.TrimEnd(), StringComparison.Ordinal);
            }
        }

        return content.Contains("</head>", StringComparison.OrdinalIgnoreCase)
            ? content.Replace("</head>", link + "</head>", StringComparison.OrdinalIgnoreCase)
            : link + content;
    }

    private static void AppendWidgetChrome(StringBuilder sb, string pageId, ArmoryLayoutWidgetDto widget)
    {
        var chrome = widget.Chrome;
        if (chrome is null)
        {
            return;
        }

        var baseSelector =
            $"[data-armory-page=\"{EscapeCss(pageId)}\"] .azp-widget[data-widget-id=\"{EscapeCss(widget.Id)}\"]";
        var selector = $"{baseSelector} .armory-panel";
        if (widget.Type is ArmoryWidgetType.PageTitle or ArmoryWidgetType.Spacer or ArmoryWidgetType.CharacterSearch
            or ArmoryWidgetType.CharacterHeader or ArmoryWidgetType.CharacterSubnav or ArmoryWidgetType.CharacterModelViewer
            or ArmoryWidgetType.MapCanvas)
        {
            selector = baseSelector;
        }

        var rules = new List<string>();

        if (chrome.BorderEnabled == false)
        {
            rules.Add("border: none");
            rules.Add("box-shadow: none");
        }
        else
        {
            if (chrome.BorderWidth is > 0)
            {
                var color = ResolveColor(chrome.BorderColor, "var(--armory-border)");
                rules.Add($"border: {chrome.BorderWidth}px solid {color}");
            }
            else if (!string.IsNullOrWhiteSpace(chrome.BorderColor))
            {
                rules.Add($"border-color: {ResolveColor(chrome.BorderColor, "var(--armory-border)")}");
            }
        }

        if (chrome.BorderRadius is >= 0)
        {
            rules.Add($"border-radius: {chrome.BorderRadius}px");
        }

        if (!string.IsNullOrWhiteSpace(chrome.BackgroundColor))
        {
            rules.Add($"background: {ResolveColor(chrome.BackgroundColor, "var(--armory-panel)")}");
        }

        if (chrome.Padding is >= 0)
        {
            rules.Add($"padding: {chrome.Padding}px");
        }

        if (chrome.Shadow is not null)
        {
            rules.Add($"box-shadow: {ShadowValue(chrome.Shadow.Value)}");
        }

        if (rules.Count == 0 && string.IsNullOrWhiteSpace(chrome.TitleColor))
        {
            return;
        }

        if (rules.Count > 0)
        {
            sb.AppendLine($"{selector} {{");
            foreach (var rule in rules)
            {
                sb.AppendLine($"  {rule};");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (!string.IsNullOrWhiteSpace(chrome.TitleColor))
        {
            sb.AppendLine($"{baseSelector} .panel-title {{");
            sb.AppendLine($"  color: {ResolveColor(chrome.TitleColor, "var(--armory-heading)")};");
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    private static string ResolveColor(string? value, string fallback)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return fallback;
        }

        return value.Trim().Equals("theme", StringComparison.OrdinalIgnoreCase) ? fallback
            : value.Trim().Equals("transparent", StringComparison.OrdinalIgnoreCase) ? "transparent"
            : value.Trim();
    }

    private static string ShadowValue(WidgetShadowPreset preset) => preset switch
    {
        WidgetShadowPreset.None => "none",
        WidgetShadowPreset.Sm => "0 1px 3px rgba(0, 0, 0, 0.35)",
        WidgetShadowPreset.Md => "0 4px 12px rgba(0, 0, 0, 0.45)",
        WidgetShadowPreset.Lg => "0 12px 32px rgba(0, 0, 0, 0.55)",
        _ => "0 2px 6px var(--armory-shadow)"
    };

    private static string EscapeCss(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
